package com.peterblackburn.shiftmanager;

public class TODO {
    /**
     * IMPORTANT TASKS
     *
     * VIEW EVENTS IN MORE DETAIL
     * ALLOW EDITING OF EXISTING EVENTS
     * EVENT FILTERING AND SORTING
     * FULLY IMPLEMENT REALM (IN PROGRESS)
     * USER PROFILES (APP SETTINGS / THEME SETTINGS / PERSONAL SHIFT + PAY SETTINGS)
     * PAYSLIP ESTIMATION
     */

    /**
     * SECONDARY TASKS
     *
     * MAKE THE APP LOOK PRETTY (IN PROGRESS)
     * IMPLEMENT THEME ENGINE
     * IMPLEMENT A FEW STANDARD THEMES FOR THE ENGINE (LIGHT, DARK ETC)
     * SHIFT TEMPLATES FOR FASTING ADDING
     */
}
